CREATE TABLE selections (
    userid integer REFERENCES userdata(userid) ON DELETE CASCADE,
    submitted boolean DEFAULT FALSE,
    DE boolean DEFAULT FALSE,
    IT boolean DEFAULT FALSE,
    EN boolean DEFAULT FALSE,
    FR boolean DEFAULT FALSE,
    LA boolean DEFAULT FALSE,
    MU boolean DEFAULT FALSE,
    KU boolean DEFAULT FALSE,
    GE boolean DEFAULT FALSE,
    EK boolean DEFAULT FALSE,
    SO boolean DEFAULT FALSE,
    EC boolean DEFAULT FALSE,
    RE boolean DEFAULT FALSE,
    ET boolean DEFAULT FALSE,
    FI boolean DEFAULT FALSE,
    ST boolean DEFAULT FALSE,
    MA boolean DEFAULT FALSE,
    PH boolean DEFAULT FALSE,
    BI boolean DEFAULT FALSE,
    CH boolean DEFAULT FALSE,
    CS boolean DEFAULT FALSE,
    SP boolean DEFAULT FALSE
)